### ISSUE TITLE
Extra timestamps

### ISSUE THREAD

**Issue by iiro** [higanworks-cookbooks/chef-client_syslog#2]
Hi,

and first of all - excellent work here! :)

Not sure if it is an issue - but I'm getting some extra timestamps to logs, for example:

Jan  7 00:06:16 hostname chef-client: [00:06:16.530746 ] [  ANY]: [2015-01-07T00:06:16+02:00] WARN: Cloning resource attributes for service[postfix] from prior resource (CHEF-3694)

How about you? The last stamp is the chef's log timestamp, but that precision timestamp I don't get. Any ideas...?

**Comment by sawanoboly** [comment]
Hi,

Please let me know more in details.
What does 'precision timestamp' mean?

- log was created?
- received by syslog?
